# Generated by Django 3.2.6 on 2022-10-03 14:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bot', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProxyOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата последнего изменения')),
                ('date_end', models.DateTimeField(verbose_name='Время окончания')),
                ('proxy_country', models.CharField(max_length=2, verbose_name='Страна')),
                ('proxy_version', models.IntegerField(verbose_name='Версия')),
                ('proxy_type', models.CharField(max_length=50, verbose_name='Тип')),
                ('auto_prolong', models.BooleanField(default=False, verbose_name='Продлевать автоматически')),
                ('active', models.BooleanField(default=True, verbose_name='Активный')),
                ('refounded', models.BooleanField(default=True, verbose_name='Деньги возвращены')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bot.user', verbose_name='Владалец')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Proxy',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата последнего изменения')),
                ('proxy_id', models.PositiveBigIntegerField(primary_key=True, serialize=False, verbose_name='Прокси id')),
                ('proxy', models.TextField(help_text='IP : PORT : USER : PASSWORD', max_length=500, verbose_name='Прокси')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proxy.proxyorder', verbose_name='Заказ')),
            ],
            options={
                'verbose_name': 'Прокси',
                'verbose_name_plural': 'Прокси',
                'ordering': ['-created_at'],
            },
        ),
    ]
