# Generated by Django 3.2.6 on 2022-09-28 09:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bot', '0002_auto_20220928_1217'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proxy',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата последнего изменения')),
                ('proxy_id', models.PositiveBigIntegerField(primary_key=True, serialize=False, verbose_name='Прокси id')),
                ('proxy', models.TextField(help_text='IP : PORT : USER : PASSWORD', max_length=500, verbose_name='Прокси')),
                ('date_end', models.DateTimeField(verbose_name='Время окончания')),
                ('version', models.IntegerField(verbose_name='Версия')),
                ('ptype', models.CharField(max_length=50, verbose_name='Тип')),
                ('country', models.CharField(max_length=2, verbose_name='Страна')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bot.user', verbose_name='Владалец')),
            ],
            options={
                'verbose_name': 'Прокси',
                'verbose_name_plural': 'Прокси',
                'ordering': ['-created_at'],
            },
        ),
    ]
