# Generated by Django 3.2.6 on 2022-10-03 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proxy', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proxy',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Создан'),
        ),
        migrations.AlterField(
            model_name='proxy',
            name='proxy',
            field=models.CharField(help_text='IP : PORT : USER : PASSWORD', max_length=500, verbose_name='Прокси'),
        ),
        migrations.AlterField(
            model_name='proxy',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Изменен'),
        ),
        migrations.AlterField(
            model_name='proxyorder',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Создан'),
        ),
        migrations.AlterField(
            model_name='proxyorder',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Изменен'),
        ),
    ]
