# Generated by Django 3.2.6 on 2022-09-30 10:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bot', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tariff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('traffic_lim', models.FloatField(default=10, verbose_name='Кол-во гб')),
                ('price', models.FloatField(default=299, verbose_name='Цена')),
                ('period', models.IntegerField(default=31, verbose_name='Период (дни)')),
                ('peers_lim', models.IntegerField(default=10, verbose_name='Кол-во подклчений')),
            ],
            options={
                'verbose_name': 'Тариф',
                'verbose_name_plural': 'Тарифы',
                'ordering': ['-price'],
            },
        ),
        migrations.CreateModel(
            name='VpnServer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=50, verbose_name='Страна')),
                ('secret', models.CharField(max_length=500, verbose_name='API KEY')),
                ('link', models.CharField(max_length=100, verbose_name='Ip addres')),
                ('traffic', models.FloatField(default=0, verbose_name='Трафик')),
                ('public_key', models.CharField(max_length=500, verbose_name='Publick key')),
            ],
            options={
                'verbose_name': 'Сервер',
                'verbose_name_plural': 'Серверы',
            },
        ),
        migrations.CreateModel(
            name='Peer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата создания')),
                ('public_key', models.CharField(max_length=500, verbose_name='Publick key')),
                ('traffic', models.FloatField(default=0, verbose_name='Трафик')),
                ('server', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vpn.vpnserver', verbose_name='Сервер')),
            ],
            options={
                'verbose_name': 'Пир',
                'verbose_name_plural': 'Пиры',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата создания')),
                ('active', models.BooleanField(default=True, verbose_name='Активный')),
                ('peers', models.ManyToManyField(to='vpn.Peer', verbose_name='Подключения')),
                ('tariff', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='vpn.tariff', verbose_name='Тариф')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bot.user', verbose_name='Владалец')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
                'ordering': ['-created_at'],
            },
        ),
    ]
