# Generated by Django 3.2.6 on 2022-10-04 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0004_auto_20221004_2002'),
        ('vpn', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Order',
            new_name='VpnOrder',
        ),
        migrations.RemoveField(
            model_name='tariff',
            name='id',
        ),
        migrations.RemoveField(
            model_name='tariff',
            name='tariff_key',
        ),
        migrations.AlterField(
            model_name='tariff',
            name='name',
            field=models.CharField(max_length=200, primary_key=True, serialize=False, verbose_name='Название'),
        ),
    ]
