# Generated by Django 3.2.6 on 2022-10-01 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='message_code',
            field=models.CharField(blank=True, default=None, help_text='Если роутинг выключен, то по данному коду в следующих сообщениях можно вывести результат пользовательского ответа.', max_length=80, null=True, verbose_name='Код сообщения'),
        ),
        migrations.AddField(
            model_name='message',
            name='need_routing',
            field=models.BooleanField(blank=True, default=True, help_text='Нужно ли искать сообщения, соответсвующие кнопкам. Используеться для создания интерактивных маршрутов.', verbose_name='Раутинг'),
        ),
    ]
